### ISSUE TITLE
Add contents to static pages

### ISSUE THREAD

**Issue by zuhao** [zuhao/isitfedoraruby#1]
Add contents to static pages, namely **Success Stories**, **How To Contribute**, and **About**.

**Comment by xiaods** [comment]
Ok, I am not clear what  the web app's target user? Could you please share more information?  I am ruby developer and also use fedora as my desktop server, I don't understand what is this web app's purpose, i guess the web app can deliver a easy way to help ruby packager to identify and streamline ruby rpm package work pipeline?

**Comment by movitto** [comment]
xiaods thanks for the interest, the main use case of the site is to promote the Fedora Ruby SIG's efforts to provide a superior platform for ruby development and deployment, as well as to provide tools and utilities to assist in the ruby to rpm migration process.

If you have any more questions feel free to send me an email directly at  mo  _at_ morsi _dot_ org. Thanks.

**Comment by xiaods** [comment]
@movitto thanks for your explanation. got it, i think i can do some contribute in this project, hold on. :-)

**Comment by nsatragno** [comment]
Closing this issue as solved :smiley:
