### ISSUE TITLE
preserve search query in URL

### ISSUE THREAD

**Issue by voxik** [zuhao/isitfedoraruby#10]
Search result has this URL:

```
http://isitfedoraruby.com/searches
```

However, there is not visible what was searched for, so I cannot send the URL. Could you change the URL, that when searching for rubygem-foo, it will look something like:

```
http://isitfedoraruby.com/searches/rubygem-foo
```

Thank you

**Comment by movitto** [comment]
Pushed areke's patch resolving this issue
