### ISSUE TITLE
Long names in bubble chart don't display

### ISSUE THREAD

**Issue by bkabrda** [zuhao/isitfedoraruby#25]
Hi guys,
the bubble chart is really great, but I'm having an issue - when I have a gem with a long name, e.g. dynamic_form, in a small bubble, I can't see its whole name. See [1]. I understand that you can't resize the bubble, but would it be possible to display the whole name of the gem in a label when I put my mouse over the bubble?

Thanks.

[1] http://www.isitfedoraruby.com/stats/bkabrda/user_rpms

**Comment by movitto** [comment]
Pushed fix to this issue
