### ISSUE TITLE
Make visible if listed bugs are closed or not

### ISSUE THREAD

**Issue by voxik** [zuhao/isitfedoraruby#47]
Currently, in the list of bugzillas [1], there is not possible to recognize if the bug was already closed or not. Could you please add this ability? I would suggest to cross the link, when the BZ is in CLOSED state. Thank you.

http://www.isitfedoraruby.com/fedorarpms/rubygem-rack-accept

**Comment by zuhao** [comment]
Thanks for the suggestion. The feature is added. Should be able to see it when the db fully reloads.

**Comment by voxik** [comment]
Wow, that is response time. Thank you :) Btw when the DB should be populated?

**Comment by zuhao** [comment]
Usually it doesn't take very long, but unfortunately there's some problem with jenkins on the server, so the newest change to the app haven't been deployed. I'm trying to reach @nicolassatragno as he is managing the deployment process on openshift server.

**Comment by nsatragno** [comment]
Hi! Sorry for taking so much time at this, I didn't see the first email. I'll take a look at it ASAP.
Happy coding!
BTW Zuhao please surround your new strings with _('') and add them in the POT file so that translators can see and translate them :-)
