### ISSUE TITLE
Link to BZ of gem review

### ISSUE THREAD

**Issue by voxik** [zuhao/isitfedoraruby#8]
It would be nice to provide the BZ with review of each rubygem. So if I search for rubygem-foo

1) and rubygem-foo is already in Fedora, there would be some additional link
2) gem is undergoing review, there would be the links to BZ with some limited informations probably, or with some message, that the gem is not yes in Fedora, but on its way into Fedora.

**Comment by movitto** [comment]
Yes agree this would be a useful feature. I would like to start pulling bugzilla and koji builds into this and cross reference and track a gem's / rpm's history through time.

I started throwing a patch together to pull in bugs related to a rubygem rpm in Fedora. It'll highlight the bz corresponding to the review request. Once thats done we can continue to expand this to associated the bz's w/ rubygems, for packages that are still in flight.

Hope to push this tomorrow or early next week.

**Comment by movitto** [comment]
BZ bugs and Koji builds are now pulled in. The bug corresponding to the review is highlighted on the rpm details page.
